<?php
 function ces_bank_services_resources() {
return array(
    'interop' => array(
      'create' => array(
        'help' => 'Creates a new transaction',
        'file' => array('file' => 'inc', 'module' => drupal_get_path('module', 'ces_bank') . '/ces_bank.interop'),
        'callback' => '_ces_bank_create',
        'access callback' => '_ces_bank_access',
        'access arguments' => array('create'),   		
		'access arguments append' => TRUE,
        'args' => array(
              array(
               'name' => 'buyer',
               'type' => 'string',
               'description' => 'The name of the buyer user',
               'source' => 'data',
               'optional' => FALSE,
             ),
             array(
               'name' => 'seller',
               'type' => 'string',
               'description' => 'The name of the seller user',
               'source' => 'data',
               'optional' => FALSE,
             ),
             array(
               'name' => 'amount',
               'type' => 'int',
               'description' => 'The amount of transanction',
               'source' => 'data',
               'optional' => FALSE,
             ),
             array(
               'name' => 'concept',
               'type' => 'string',
               'description' => 'A concept for transaction',
               'source' => 'data',
               'optional' => FALSE,
             ),
        ),
      ),
      'update' => array(
        'help' => 'Applys a transaction',
        'file' => array('file' => 'inc', 'module' => drupal_get_path('module', 'ces_bank') . '/ces_bank.interop'),
        'callback' => '_ces_bank_update',
        'access callback' => '_ces_bank_access',
        'access arguments' => array('interop resource update'),
        'access arguments append' => FALSE,
        'args' => array(
              array(
               'name' => 'id',
               'type' => 'string',
               'description' => 'The id of the transaction',
               'source' => 'data',
               'optional' => FALSE,
             ),             
        ),
      ),
	'index' => array(
	'help' => 'Retrieves user or transaction',
	'file' => array('file' => 'inc', 'module' => drupal_get_path('module', 'ces_bank') . '/ces_bank.interop'),
	'callback' => '_ces_bank_index',
	'access callback' => '_ces_bank_access',
	'access arguments' => array('access content'),
	'access arguments append' => FALSE,
	'args' => array(
   	array(
            'name' => 'type',
            'type' => 'string',
            'description' => '',
            'source' => array(
              'param' => 'type',
            ),
            'optional' => FALSE,
          ),
          array(
           'name' => 'id',
           'type' => 'int',
           'description' => 'id transaction or account name',
           'source' => array( 'param'=>'id'),
           'optional' => FALSE,
          ),
	 ),
       ),   
     ),
   );
 }
